#version: '3.8'
#
#services:
#  postgres:
#    image: postgres:14-alpine
#    environment:
#      POSTGRES_DB: postgres
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: admin123
#    ports:
#      - "5432:5432"
#    healthcheck:
#          test: ["CMD", "pg_isready", "-h", "localhost", "-p", "5432"]
#          interval: 10s
#          timeout: 5s
#          retries: 5
#
#  clickhouse:
#    image: clickhouse/clickhouse-server:23.3-alpine
#    ports:
#      - "8123:8123"
#      - "9000:9000"
#    ulimits:
#      nofile:
#        soft: 262144
#        hard: 262144
#    healthcheck:
#      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping" ]
#      interval: 30s
#      timeout: 5s
#      retries: 3
#  benchmark:
#    build: .
#    container_name: compare_pg_clickh-benchmark
#    depends_on:
#      postgres:
#        condition: service_healthy
#      clickhouse:
#        condition: service_healthy
#    env_file:
#      - .env
#    volumes:
#      - ./results:/app

version: '3.8'

services:

  benchmark:
    image: compare_pg_clickh-benchmark
    environment:
      - CLICKHOUSE_URL=jdbc:clickhouse://clickhouse:8123/default?compress=0
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - RECORD_COUNT=2000000
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_started
    volumes:
      - ./results:/app/results

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:23.3-alpine
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8123/ping"]
#      interval: 10s
#      timeout: 5s
#      retries: 3
#      start_period: 30s # Дать время на старт сервиса

